/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>color Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.operations.colorConfiguration#getColor <em>Color</em>}</li>
 *   <li>{@link org.xtext.operations.colorConfiguration#getH_min <em>Hmin</em>}</li>
 *   <li>{@link org.xtext.operations.colorConfiguration#getS_min <em>Smin</em>}</li>
 *   <li>{@link org.xtext.operations.colorConfiguration#getV_min <em>Vmin</em>}</li>
 *   <li>{@link org.xtext.operations.colorConfiguration#getH_max <em>Hmax</em>}</li>
 *   <li>{@link org.xtext.operations.colorConfiguration#getS_max <em>Smax</em>}</li>
 *   <li>{@link org.xtext.operations.colorConfiguration#getV_max <em>Vmax</em>}</li>
 * </ul>
 *
 * @see org.xtext.operations.OperationsPackage#getcolorConfiguration()
 * @model
 * @generated
 */
public interface colorConfiguration extends Command
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.Color}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' containment reference list.
   * @see org.xtext.operations.OperationsPackage#getcolorConfiguration_Color()
   * @model containment="true"
   * @generated
   */
  EList<Color> getColor();

  /**
   * Returns the value of the '<em><b>Hmin</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.H_min}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hmin</em>' containment reference list.
   * @see org.xtext.operations.OperationsPackage#getcolorConfiguration_H_min()
   * @model containment="true"
   * @generated
   */
  EList<H_min> getH_min();

  /**
   * Returns the value of the '<em><b>Smin</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.S_min}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smin</em>' containment reference list.
   * @see org.xtext.operations.OperationsPackage#getcolorConfiguration_S_min()
   * @model containment="true"
   * @generated
   */
  EList<S_min> getS_min();

  /**
   * Returns the value of the '<em><b>Vmin</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.V_min}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vmin</em>' containment reference list.
   * @see org.xtext.operations.OperationsPackage#getcolorConfiguration_V_min()
   * @model containment="true"
   * @generated
   */
  EList<V_min> getV_min();

  /**
   * Returns the value of the '<em><b>Hmax</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.H_max}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hmax</em>' containment reference list.
   * @see org.xtext.operations.OperationsPackage#getcolorConfiguration_H_max()
   * @model containment="true"
   * @generated
   */
  EList<H_max> getH_max();

  /**
   * Returns the value of the '<em><b>Smax</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.S_max}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smax</em>' containment reference list.
   * @see org.xtext.operations.OperationsPackage#getcolorConfiguration_S_max()
   * @model containment="true"
   * @generated
   */
  EList<S_max> getS_max();

  /**
   * Returns the value of the '<em><b>Vmax</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.V_max}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vmax</em>' containment reference list.
   * @see org.xtext.operations.OperationsPackage#getcolorConfiguration_V_max()
   * @model containment="true"
   * @generated
   */
  EList<V_max> getV_max();

} // colorConfiguration
