/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hmax</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.operations.H_max#getH_max <em>Hmax</em>}</li>
 * </ul>
 *
 * @see org.xtext.operations.OperationsPackage#getH_max()
 * @model
 * @generated
 */
public interface H_max extends EObject
{
  /**
   * Returns the value of the '<em><b>Hmax</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hmax</em>' attribute.
   * @see #setH_max(int)
   * @see org.xtext.operations.OperationsPackage#getH_max_H_max()
   * @model
   * @generated
   */
  int getH_max();

  /**
   * Sets the value of the '{@link org.xtext.operations.H_max#getH_max <em>Hmax</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hmax</em>' attribute.
   * @see #getH_max()
   * @generated
   */
  void setH_max(int value);

} // H_max
