/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.operations.OperationsFactory
 * @model kind="package"
 * @generated
 */
public interface OperationsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "operations";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/Operations";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "operations";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OperationsPackage eINSTANCE = org.xtext.operations.impl.OperationsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.InitialImpl <em>Initial</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.InitialImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getInitial()
   * @generated
   */
  int INITIAL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL__TIME = 1;

  /**
   * The number of structural features of the '<em>Initial</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.CommandImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__NAME = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.lightRGBImpl <em>light RGB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.lightRGBImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getlightRGB()
   * @generated
   */
  int LIGHT_RGB = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGHT_RGB__NAME = COMMAND__NAME;

  /**
   * The feature id for the '<em><b>R</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGHT_RGB__R = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>G</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGHT_RGB__G = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGHT_RGB__B = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>light RGB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGHT_RGB_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.buzzerOffImpl <em>buzzer Off</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.buzzerOffImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getbuzzerOff()
   * @generated
   */
  int BUZZER_OFF = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUZZER_OFF__NAME = COMMAND__NAME;

  /**
   * The number of structural features of the '<em>buzzer Off</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUZZER_OFF_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.buzzerOnImpl <em>buzzer On</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.buzzerOnImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getbuzzerOn()
   * @generated
   */
  int BUZZER_ON = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUZZER_ON__NAME = COMMAND__NAME;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUZZER_ON__TIME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>buzzer On</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUZZER_ON_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.calibrationImpl <em>calibration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.calibrationImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getcalibration()
   * @generated
   */
  int CALIBRATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION__NAME = COMMAND__NAME;

  /**
   * The feature id for the '<em><b>Color</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION__COLOR = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Hmin</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION__HMIN = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Smin</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION__SMIN = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Vmin</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION__VMIN = COMMAND_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Hmax</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION__HMAX = COMMAND_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Smax</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION__SMAX = COMMAND_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Vmax</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION__VMAX = COMMAND_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>calibration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALIBRATION_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.cameraColorImpl <em>camera Color</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.cameraColorImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getcameraColor()
   * @generated
   */
  int CAMERA_COLOR = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_COLOR__NAME = COMMAND__NAME;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_COLOR__TIME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>camera Color</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMERA_COLOR_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.readAllServosImpl <em>read All Servos</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.readAllServosImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getreadAllServos()
   * @generated
   */
  int READ_ALL_SERVOS = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_ALL_SERVOS__NAME = COMMAND__NAME;

  /**
   * The number of structural features of the '<em>read All Servos</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_ALL_SERVOS_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.readServoImpl <em>read Servo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.readServoImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getreadServo()
   * @generated
   */
  int READ_SERVO = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_SERVO__NAME = COMMAND__NAME;

  /**
   * The feature id for the '<em><b>Servo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_SERVO__SERVO = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>read Servo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_SERVO_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.rotateServoImpl <em>rotate Servo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.rotateServoImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getrotateServo()
   * @generated
   */
  int ROTATE_SERVO = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_SERVO__NAME = COMMAND__NAME;

  /**
   * The feature id for the '<em><b>Servo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_SERVO__SERVO = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Angle</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_SERVO__ANGLE = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_SERVO__TIME = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>rotate Servo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_SERVO_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.rotateAllServosImpl <em>rotate All Servos</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.rotateAllServosImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getrotateAllServos()
   * @generated
   */
  int ROTATE_ALL_SERVOS = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS__NAME = COMMAND__NAME;

  /**
   * The feature id for the '<em><b>Angle1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS__ANGLE1 = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Angle2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS__ANGLE2 = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Angle3</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS__ANGLE3 = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Angle4</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS__ANGLE4 = COMMAND_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Angle5</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS__ANGLE5 = COMMAND_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Angle6</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS__ANGLE6 = COMMAND_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS__TIME = COMMAND_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>rotate All Servos</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_ALL_SERVOS_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.ResultImpl <em>Result</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.ResultImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getResult()
   * @generated
   */
  int RESULT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__NAME = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__TIME = 1;

  /**
   * The number of structural features of the '<em>Result</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.ConditionsImpl <em>Conditions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.ConditionsImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getConditions()
   * @generated
   */
  int CONDITIONS = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONS__NAME = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONS__TIME = 1;

  /**
   * The number of structural features of the '<em>Conditions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.SolutionImpl <em>Solution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.SolutionImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getSolution()
   * @generated
   */
  int SOLUTION = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLUTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Angle res</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLUTION__ANGLE_RES = 1;

  /**
   * The number of structural features of the '<em>Solution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLUTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.isAtSingleImpl <em>is At Single</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.isAtSingleImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getisAtSingle()
   * @generated
   */
  int IS_AT_SINGLE = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT_SINGLE__NAME = SOLUTION__NAME;

  /**
   * The feature id for the '<em><b>Angle res</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT_SINGLE__ANGLE_RES = SOLUTION__ANGLE_RES;

  /**
   * The feature id for the '<em><b>Servo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT_SINGLE__SERVO = SOLUTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Angle</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT_SINGLE__ANGLE = SOLUTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>is At Single</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT_SINGLE_FEATURE_COUNT = SOLUTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.isAtImpl <em>is At</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.isAtImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getisAt()
   * @generated
   */
  int IS_AT = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT__NAME = SOLUTION__NAME;

  /**
   * The feature id for the '<em><b>Angle res</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT__ANGLE_RES = SOLUTION__ANGLE_RES;

  /**
   * The feature id for the '<em><b>Angle1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT__ANGLE1 = SOLUTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Angle2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT__ANGLE2 = SOLUTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Angle3</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT__ANGLE3 = SOLUTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Angle4</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT__ANGLE4 = SOLUTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Angle5</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT__ANGLE5 = SOLUTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Angle6</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT__ANGLE6 = SOLUTION_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>is At</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_AT_FEATURE_COUNT = SOLUTION_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.Angle_resImpl <em>Angle res</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.Angle_resImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getAngle_res()
   * @generated
   */
  int ANGLE_RES = 16;

  /**
   * The feature id for the '<em><b>Angle res</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANGLE_RES__ANGLE_RES = 0;

  /**
   * The number of structural features of the '<em>Angle res</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANGLE_RES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.AngleImpl <em>Angle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.AngleImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getAngle()
   * @generated
   */
  int ANGLE = 17;

  /**
   * The feature id for the '<em><b>Angle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANGLE__ANGLE = 0;

  /**
   * The number of structural features of the '<em>Angle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANGLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.TimeImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getTime()
   * @generated
   */
  int TIME = 18;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__TIME = 0;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.ServoImpl <em>Servo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.ServoImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getServo()
   * @generated
   */
  int SERVO = 19;

  /**
   * The feature id for the '<em><b>Servo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVO__SERVO = 0;

  /**
   * The number of structural features of the '<em>Servo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.V_maxImpl <em>Vmax</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.V_maxImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getV_max()
   * @generated
   */
  int VMAX = 20;

  /**
   * The feature id for the '<em><b>Vmax</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VMAX__VMAX = 0;

  /**
   * The number of structural features of the '<em>Vmax</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VMAX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.S_maxImpl <em>Smax</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.S_maxImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getS_max()
   * @generated
   */
  int SMAX = 21;

  /**
   * The feature id for the '<em><b>Smax</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMAX__SMAX = 0;

  /**
   * The number of structural features of the '<em>Smax</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMAX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.H_maxImpl <em>Hmax</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.H_maxImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getH_max()
   * @generated
   */
  int HMAX = 22;

  /**
   * The feature id for the '<em><b>Hmax</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HMAX__HMAX = 0;

  /**
   * The number of structural features of the '<em>Hmax</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HMAX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.V_minImpl <em>Vmin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.V_minImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getV_min()
   * @generated
   */
  int VMIN = 23;

  /**
   * The feature id for the '<em><b>Vmin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VMIN__VMIN = 0;

  /**
   * The number of structural features of the '<em>Vmin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VMIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.S_minImpl <em>Smin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.S_minImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getS_min()
   * @generated
   */
  int SMIN = 24;

  /**
   * The feature id for the '<em><b>Smin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMIN__SMIN = 0;

  /**
   * The number of structural features of the '<em>Smin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.H_minImpl <em>Hmin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.H_minImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getH_min()
   * @generated
   */
  int HMIN = 25;

  /**
   * The feature id for the '<em><b>Hmin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HMIN__HMIN = 0;

  /**
   * The number of structural features of the '<em>Hmin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HMIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.ColorImpl <em>Color</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.ColorImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getColor()
   * @generated
   */
  int COLOR = 26;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__COLOR = 0;

  /**
   * The number of structural features of the '<em>Color</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.BImpl <em>B</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.BImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getB()
   * @generated
   */
  int B = 27;

  /**
   * The feature id for the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int B__B = 0;

  /**
   * The number of structural features of the '<em>B</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int B_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.GImpl <em>G</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.GImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getG()
   * @generated
   */
  int G = 28;

  /**
   * The feature id for the '<em><b>G</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int G__G = 0;

  /**
   * The number of structural features of the '<em>G</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int G_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.operations.impl.RImpl <em>R</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.operations.impl.RImpl
   * @see org.xtext.operations.impl.OperationsPackageImpl#getR()
   * @generated
   */
  int R = 29;

  /**
   * The feature id for the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int R__R = 0;

  /**
   * The number of structural features of the '<em>R</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int R_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.operations.Initial <em>Initial</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial</em>'.
   * @see org.xtext.operations.Initial
   * @generated
   */
  EClass getInitial();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Initial#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.operations.Initial#getName()
   * @see #getInitial()
   * @generated
   */
  EAttribute getInitial_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.Initial#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.operations.Initial#getTime()
   * @see #getInitial()
   * @generated
   */
  EReference getInitial_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.operations.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Command#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.operations.Command#getName()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.lightRGB <em>light RGB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>light RGB</em>'.
   * @see org.xtext.operations.lightRGB
   * @generated
   */
  EClass getlightRGB();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.lightRGB#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>R</em>'.
   * @see org.xtext.operations.lightRGB#getR()
   * @see #getlightRGB()
   * @generated
   */
  EReference getlightRGB_R();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.lightRGB#getG <em>G</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>G</em>'.
   * @see org.xtext.operations.lightRGB#getG()
   * @see #getlightRGB()
   * @generated
   */
  EReference getlightRGB_G();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.lightRGB#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>B</em>'.
   * @see org.xtext.operations.lightRGB#getB()
   * @see #getlightRGB()
   * @generated
   */
  EReference getlightRGB_B();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.buzzerOff <em>buzzer Off</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>buzzer Off</em>'.
   * @see org.xtext.operations.buzzerOff
   * @generated
   */
  EClass getbuzzerOff();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.buzzerOn <em>buzzer On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>buzzer On</em>'.
   * @see org.xtext.operations.buzzerOn
   * @generated
   */
  EClass getbuzzerOn();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.buzzerOn#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.operations.buzzerOn#getTime()
   * @see #getbuzzerOn()
   * @generated
   */
  EReference getbuzzerOn_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.calibration <em>calibration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>calibration</em>'.
   * @see org.xtext.operations.calibration
   * @generated
   */
  EClass getcalibration();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.calibration#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Color</em>'.
   * @see org.xtext.operations.calibration#getColor()
   * @see #getcalibration()
   * @generated
   */
  EReference getcalibration_Color();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.calibration#getH_min <em>Hmin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hmin</em>'.
   * @see org.xtext.operations.calibration#getH_min()
   * @see #getcalibration()
   * @generated
   */
  EReference getcalibration_H_min();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.calibration#getS_min <em>Smin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Smin</em>'.
   * @see org.xtext.operations.calibration#getS_min()
   * @see #getcalibration()
   * @generated
   */
  EReference getcalibration_S_min();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.calibration#getV_min <em>Vmin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vmin</em>'.
   * @see org.xtext.operations.calibration#getV_min()
   * @see #getcalibration()
   * @generated
   */
  EReference getcalibration_V_min();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.calibration#getH_max <em>Hmax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hmax</em>'.
   * @see org.xtext.operations.calibration#getH_max()
   * @see #getcalibration()
   * @generated
   */
  EReference getcalibration_H_max();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.calibration#getS_max <em>Smax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Smax</em>'.
   * @see org.xtext.operations.calibration#getS_max()
   * @see #getcalibration()
   * @generated
   */
  EReference getcalibration_S_max();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.calibration#getV_max <em>Vmax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vmax</em>'.
   * @see org.xtext.operations.calibration#getV_max()
   * @see #getcalibration()
   * @generated
   */
  EReference getcalibration_V_max();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.cameraColor <em>camera Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>camera Color</em>'.
   * @see org.xtext.operations.cameraColor
   * @generated
   */
  EClass getcameraColor();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.cameraColor#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.operations.cameraColor#getTime()
   * @see #getcameraColor()
   * @generated
   */
  EReference getcameraColor_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.readAllServos <em>read All Servos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>read All Servos</em>'.
   * @see org.xtext.operations.readAllServos
   * @generated
   */
  EClass getreadAllServos();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.readServo <em>read Servo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>read Servo</em>'.
   * @see org.xtext.operations.readServo
   * @generated
   */
  EClass getreadServo();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.readServo#getServo <em>Servo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servo</em>'.
   * @see org.xtext.operations.readServo#getServo()
   * @see #getreadServo()
   * @generated
   */
  EReference getreadServo_Servo();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.rotateServo <em>rotate Servo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rotate Servo</em>'.
   * @see org.xtext.operations.rotateServo
   * @generated
   */
  EClass getrotateServo();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateServo#getServo <em>Servo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servo</em>'.
   * @see org.xtext.operations.rotateServo#getServo()
   * @see #getrotateServo()
   * @generated
   */
  EReference getrotateServo_Servo();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateServo#getAngle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle</em>'.
   * @see org.xtext.operations.rotateServo#getAngle()
   * @see #getrotateServo()
   * @generated
   */
  EReference getrotateServo_Angle();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateServo#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.operations.rotateServo#getTime()
   * @see #getrotateServo()
   * @generated
   */
  EReference getrotateServo_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.rotateAllServos <em>rotate All Servos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rotate All Servos</em>'.
   * @see org.xtext.operations.rotateAllServos
   * @generated
   */
  EClass getrotateAllServos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateAllServos#getAngle1 <em>Angle1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle1</em>'.
   * @see org.xtext.operations.rotateAllServos#getAngle1()
   * @see #getrotateAllServos()
   * @generated
   */
  EReference getrotateAllServos_Angle1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateAllServos#getAngle2 <em>Angle2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle2</em>'.
   * @see org.xtext.operations.rotateAllServos#getAngle2()
   * @see #getrotateAllServos()
   * @generated
   */
  EReference getrotateAllServos_Angle2();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateAllServos#getAngle3 <em>Angle3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle3</em>'.
   * @see org.xtext.operations.rotateAllServos#getAngle3()
   * @see #getrotateAllServos()
   * @generated
   */
  EReference getrotateAllServos_Angle3();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateAllServos#getAngle4 <em>Angle4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle4</em>'.
   * @see org.xtext.operations.rotateAllServos#getAngle4()
   * @see #getrotateAllServos()
   * @generated
   */
  EReference getrotateAllServos_Angle4();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateAllServos#getAngle5 <em>Angle5</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle5</em>'.
   * @see org.xtext.operations.rotateAllServos#getAngle5()
   * @see #getrotateAllServos()
   * @generated
   */
  EReference getrotateAllServos_Angle5();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateAllServos#getAngle6 <em>Angle6</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle6</em>'.
   * @see org.xtext.operations.rotateAllServos#getAngle6()
   * @see #getrotateAllServos()
   * @generated
   */
  EReference getrotateAllServos_Angle6();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.rotateAllServos#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.operations.rotateAllServos#getTime()
   * @see #getrotateAllServos()
   * @generated
   */
  EReference getrotateAllServos_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Result <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Result</em>'.
   * @see org.xtext.operations.Result
   * @generated
   */
  EClass getResult();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Result#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.operations.Result#getName()
   * @see #getResult()
   * @generated
   */
  EAttribute getResult_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.Result#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.operations.Result#getTime()
   * @see #getResult()
   * @generated
   */
  EReference getResult_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Conditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditions</em>'.
   * @see org.xtext.operations.Conditions
   * @generated
   */
  EClass getConditions();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Conditions#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.operations.Conditions#getName()
   * @see #getConditions()
   * @generated
   */
  EAttribute getConditions_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.Conditions#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.operations.Conditions#getTime()
   * @see #getConditions()
   * @generated
   */
  EReference getConditions_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Solution <em>Solution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Solution</em>'.
   * @see org.xtext.operations.Solution
   * @generated
   */
  EClass getSolution();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Solution#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.operations.Solution#getName()
   * @see #getSolution()
   * @generated
   */
  EAttribute getSolution_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.Solution#getAngle_res <em>Angle res</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle res</em>'.
   * @see org.xtext.operations.Solution#getAngle_res()
   * @see #getSolution()
   * @generated
   */
  EReference getSolution_Angle_res();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.isAtSingle <em>is At Single</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>is At Single</em>'.
   * @see org.xtext.operations.isAtSingle
   * @generated
   */
  EClass getisAtSingle();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.isAtSingle#getServo <em>Servo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servo</em>'.
   * @see org.xtext.operations.isAtSingle#getServo()
   * @see #getisAtSingle()
   * @generated
   */
  EReference getisAtSingle_Servo();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.isAtSingle#getAngle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle</em>'.
   * @see org.xtext.operations.isAtSingle#getAngle()
   * @see #getisAtSingle()
   * @generated
   */
  EReference getisAtSingle_Angle();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.isAt <em>is At</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>is At</em>'.
   * @see org.xtext.operations.isAt
   * @generated
   */
  EClass getisAt();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.isAt#getAngle1 <em>Angle1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle1</em>'.
   * @see org.xtext.operations.isAt#getAngle1()
   * @see #getisAt()
   * @generated
   */
  EReference getisAt_Angle1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.isAt#getAngle2 <em>Angle2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle2</em>'.
   * @see org.xtext.operations.isAt#getAngle2()
   * @see #getisAt()
   * @generated
   */
  EReference getisAt_Angle2();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.isAt#getAngle3 <em>Angle3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle3</em>'.
   * @see org.xtext.operations.isAt#getAngle3()
   * @see #getisAt()
   * @generated
   */
  EReference getisAt_Angle3();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.isAt#getAngle4 <em>Angle4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle4</em>'.
   * @see org.xtext.operations.isAt#getAngle4()
   * @see #getisAt()
   * @generated
   */
  EReference getisAt_Angle4();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.isAt#getAngle5 <em>Angle5</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle5</em>'.
   * @see org.xtext.operations.isAt#getAngle5()
   * @see #getisAt()
   * @generated
   */
  EReference getisAt_Angle5();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.operations.isAt#getAngle6 <em>Angle6</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Angle6</em>'.
   * @see org.xtext.operations.isAt#getAngle6()
   * @see #getisAt()
   * @generated
   */
  EReference getisAt_Angle6();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Angle_res <em>Angle res</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Angle res</em>'.
   * @see org.xtext.operations.Angle_res
   * @generated
   */
  EClass getAngle_res();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Angle_res#getAngle_res <em>Angle res</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Angle res</em>'.
   * @see org.xtext.operations.Angle_res#getAngle_res()
   * @see #getAngle_res()
   * @generated
   */
  EAttribute getAngle_res_Angle_res();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Angle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Angle</em>'.
   * @see org.xtext.operations.Angle
   * @generated
   */
  EClass getAngle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Angle#getAngle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Angle</em>'.
   * @see org.xtext.operations.Angle#getAngle()
   * @see #getAngle()
   * @generated
   */
  EAttribute getAngle_Angle();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.operations.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Time#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.operations.Time#getTime()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Servo <em>Servo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Servo</em>'.
   * @see org.xtext.operations.Servo
   * @generated
   */
  EClass getServo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Servo#getServo <em>Servo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Servo</em>'.
   * @see org.xtext.operations.Servo#getServo()
   * @see #getServo()
   * @generated
   */
  EAttribute getServo_Servo();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.V_max <em>Vmax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vmax</em>'.
   * @see org.xtext.operations.V_max
   * @generated
   */
  EClass getV_max();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.V_max#getV_max <em>Vmax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vmax</em>'.
   * @see org.xtext.operations.V_max#getV_max()
   * @see #getV_max()
   * @generated
   */
  EAttribute getV_max_V_max();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.S_max <em>Smax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Smax</em>'.
   * @see org.xtext.operations.S_max
   * @generated
   */
  EClass getS_max();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.S_max#getS_max <em>Smax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Smax</em>'.
   * @see org.xtext.operations.S_max#getS_max()
   * @see #getS_max()
   * @generated
   */
  EAttribute getS_max_S_max();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.H_max <em>Hmax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hmax</em>'.
   * @see org.xtext.operations.H_max
   * @generated
   */
  EClass getH_max();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.H_max#getH_max <em>Hmax</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hmax</em>'.
   * @see org.xtext.operations.H_max#getH_max()
   * @see #getH_max()
   * @generated
   */
  EAttribute getH_max_H_max();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.V_min <em>Vmin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vmin</em>'.
   * @see org.xtext.operations.V_min
   * @generated
   */
  EClass getV_min();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.V_min#getV_min <em>Vmin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vmin</em>'.
   * @see org.xtext.operations.V_min#getV_min()
   * @see #getV_min()
   * @generated
   */
  EAttribute getV_min_V_min();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.S_min <em>Smin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Smin</em>'.
   * @see org.xtext.operations.S_min
   * @generated
   */
  EClass getS_min();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.S_min#getS_min <em>Smin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Smin</em>'.
   * @see org.xtext.operations.S_min#getS_min()
   * @see #getS_min()
   * @generated
   */
  EAttribute getS_min_S_min();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.H_min <em>Hmin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hmin</em>'.
   * @see org.xtext.operations.H_min
   * @generated
   */
  EClass getH_min();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.H_min#getH_min <em>Hmin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hmin</em>'.
   * @see org.xtext.operations.H_min#getH_min()
   * @see #getH_min()
   * @generated
   */
  EAttribute getH_min_H_min();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color</em>'.
   * @see org.xtext.operations.Color
   * @generated
   */
  EClass getColor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.Color#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.operations.Color#getColor()
   * @see #getColor()
   * @generated
   */
  EAttribute getColor_Color();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.B <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>B</em>'.
   * @see org.xtext.operations.B
   * @generated
   */
  EClass getB();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.B#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>B</em>'.
   * @see org.xtext.operations.B#getB()
   * @see #getB()
   * @generated
   */
  EAttribute getB_B();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.G <em>G</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>G</em>'.
   * @see org.xtext.operations.G
   * @generated
   */
  EClass getG();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.G#getG <em>G</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>G</em>'.
   * @see org.xtext.operations.G#getG()
   * @see #getG()
   * @generated
   */
  EAttribute getG_G();

  /**
   * Returns the meta object for class '{@link org.xtext.operations.R <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>R</em>'.
   * @see org.xtext.operations.R
   * @generated
   */
  EClass getR();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.operations.R#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>R</em>'.
   * @see org.xtext.operations.R#getR()
   * @see #getR()
   * @generated
   */
  EAttribute getR_R();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  OperationsFactory getOperationsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.InitialImpl <em>Initial</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.InitialImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getInitial()
     * @generated
     */
    EClass INITIAL = eINSTANCE.getInitial();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIAL__NAME = eINSTANCE.getInitial_Name();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL__TIME = eINSTANCE.getInitial_Time();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.CommandImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__NAME = eINSTANCE.getCommand_Name();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.lightRGBImpl <em>light RGB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.lightRGBImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getlightRGB()
     * @generated
     */
    EClass LIGHT_RGB = eINSTANCE.getlightRGB();

    /**
     * The meta object literal for the '<em><b>R</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGHT_RGB__R = eINSTANCE.getlightRGB_R();

    /**
     * The meta object literal for the '<em><b>G</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGHT_RGB__G = eINSTANCE.getlightRGB_G();

    /**
     * The meta object literal for the '<em><b>B</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGHT_RGB__B = eINSTANCE.getlightRGB_B();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.buzzerOffImpl <em>buzzer Off</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.buzzerOffImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getbuzzerOff()
     * @generated
     */
    EClass BUZZER_OFF = eINSTANCE.getbuzzerOff();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.buzzerOnImpl <em>buzzer On</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.buzzerOnImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getbuzzerOn()
     * @generated
     */
    EClass BUZZER_ON = eINSTANCE.getbuzzerOn();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUZZER_ON__TIME = eINSTANCE.getbuzzerOn_Time();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.calibrationImpl <em>calibration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.calibrationImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getcalibration()
     * @generated
     */
    EClass CALIBRATION = eINSTANCE.getcalibration();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALIBRATION__COLOR = eINSTANCE.getcalibration_Color();

    /**
     * The meta object literal for the '<em><b>Hmin</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALIBRATION__HMIN = eINSTANCE.getcalibration_H_min();

    /**
     * The meta object literal for the '<em><b>Smin</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALIBRATION__SMIN = eINSTANCE.getcalibration_S_min();

    /**
     * The meta object literal for the '<em><b>Vmin</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALIBRATION__VMIN = eINSTANCE.getcalibration_V_min();

    /**
     * The meta object literal for the '<em><b>Hmax</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALIBRATION__HMAX = eINSTANCE.getcalibration_H_max();

    /**
     * The meta object literal for the '<em><b>Smax</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALIBRATION__SMAX = eINSTANCE.getcalibration_S_max();

    /**
     * The meta object literal for the '<em><b>Vmax</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALIBRATION__VMAX = eINSTANCE.getcalibration_V_max();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.cameraColorImpl <em>camera Color</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.cameraColorImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getcameraColor()
     * @generated
     */
    EClass CAMERA_COLOR = eINSTANCE.getcameraColor();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMERA_COLOR__TIME = eINSTANCE.getcameraColor_Time();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.readAllServosImpl <em>read All Servos</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.readAllServosImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getreadAllServos()
     * @generated
     */
    EClass READ_ALL_SERVOS = eINSTANCE.getreadAllServos();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.readServoImpl <em>read Servo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.readServoImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getreadServo()
     * @generated
     */
    EClass READ_SERVO = eINSTANCE.getreadServo();

    /**
     * The meta object literal for the '<em><b>Servo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference READ_SERVO__SERVO = eINSTANCE.getreadServo_Servo();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.rotateServoImpl <em>rotate Servo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.rotateServoImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getrotateServo()
     * @generated
     */
    EClass ROTATE_SERVO = eINSTANCE.getrotateServo();

    /**
     * The meta object literal for the '<em><b>Servo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_SERVO__SERVO = eINSTANCE.getrotateServo_Servo();

    /**
     * The meta object literal for the '<em><b>Angle</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_SERVO__ANGLE = eINSTANCE.getrotateServo_Angle();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_SERVO__TIME = eINSTANCE.getrotateServo_Time();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.rotateAllServosImpl <em>rotate All Servos</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.rotateAllServosImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getrotateAllServos()
     * @generated
     */
    EClass ROTATE_ALL_SERVOS = eINSTANCE.getrotateAllServos();

    /**
     * The meta object literal for the '<em><b>Angle1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_ALL_SERVOS__ANGLE1 = eINSTANCE.getrotateAllServos_Angle1();

    /**
     * The meta object literal for the '<em><b>Angle2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_ALL_SERVOS__ANGLE2 = eINSTANCE.getrotateAllServos_Angle2();

    /**
     * The meta object literal for the '<em><b>Angle3</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_ALL_SERVOS__ANGLE3 = eINSTANCE.getrotateAllServos_Angle3();

    /**
     * The meta object literal for the '<em><b>Angle4</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_ALL_SERVOS__ANGLE4 = eINSTANCE.getrotateAllServos_Angle4();

    /**
     * The meta object literal for the '<em><b>Angle5</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_ALL_SERVOS__ANGLE5 = eINSTANCE.getrotateAllServos_Angle5();

    /**
     * The meta object literal for the '<em><b>Angle6</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_ALL_SERVOS__ANGLE6 = eINSTANCE.getrotateAllServos_Angle6();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATE_ALL_SERVOS__TIME = eINSTANCE.getrotateAllServos_Time();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.ResultImpl <em>Result</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.ResultImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getResult()
     * @generated
     */
    EClass RESULT = eINSTANCE.getResult();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESULT__NAME = eINSTANCE.getResult_Name();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESULT__TIME = eINSTANCE.getResult_Time();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.ConditionsImpl <em>Conditions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.ConditionsImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getConditions()
     * @generated
     */
    EClass CONDITIONS = eINSTANCE.getConditions();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONS__NAME = eINSTANCE.getConditions_Name();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONS__TIME = eINSTANCE.getConditions_Time();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.SolutionImpl <em>Solution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.SolutionImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getSolution()
     * @generated
     */
    EClass SOLUTION = eINSTANCE.getSolution();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOLUTION__NAME = eINSTANCE.getSolution_Name();

    /**
     * The meta object literal for the '<em><b>Angle res</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOLUTION__ANGLE_RES = eINSTANCE.getSolution_Angle_res();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.isAtSingleImpl <em>is At Single</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.isAtSingleImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getisAtSingle()
     * @generated
     */
    EClass IS_AT_SINGLE = eINSTANCE.getisAtSingle();

    /**
     * The meta object literal for the '<em><b>Servo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_AT_SINGLE__SERVO = eINSTANCE.getisAtSingle_Servo();

    /**
     * The meta object literal for the '<em><b>Angle</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_AT_SINGLE__ANGLE = eINSTANCE.getisAtSingle_Angle();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.isAtImpl <em>is At</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.isAtImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getisAt()
     * @generated
     */
    EClass IS_AT = eINSTANCE.getisAt();

    /**
     * The meta object literal for the '<em><b>Angle1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_AT__ANGLE1 = eINSTANCE.getisAt_Angle1();

    /**
     * The meta object literal for the '<em><b>Angle2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_AT__ANGLE2 = eINSTANCE.getisAt_Angle2();

    /**
     * The meta object literal for the '<em><b>Angle3</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_AT__ANGLE3 = eINSTANCE.getisAt_Angle3();

    /**
     * The meta object literal for the '<em><b>Angle4</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_AT__ANGLE4 = eINSTANCE.getisAt_Angle4();

    /**
     * The meta object literal for the '<em><b>Angle5</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_AT__ANGLE5 = eINSTANCE.getisAt_Angle5();

    /**
     * The meta object literal for the '<em><b>Angle6</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_AT__ANGLE6 = eINSTANCE.getisAt_Angle6();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.Angle_resImpl <em>Angle res</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.Angle_resImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getAngle_res()
     * @generated
     */
    EClass ANGLE_RES = eINSTANCE.getAngle_res();

    /**
     * The meta object literal for the '<em><b>Angle res</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANGLE_RES__ANGLE_RES = eINSTANCE.getAngle_res_Angle_res();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.AngleImpl <em>Angle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.AngleImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getAngle()
     * @generated
     */
    EClass ANGLE = eINSTANCE.getAngle();

    /**
     * The meta object literal for the '<em><b>Angle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANGLE__ANGLE = eINSTANCE.getAngle_Angle();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.TimeImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__TIME = eINSTANCE.getTime_Time();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.ServoImpl <em>Servo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.ServoImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getServo()
     * @generated
     */
    EClass SERVO = eINSTANCE.getServo();

    /**
     * The meta object literal for the '<em><b>Servo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVO__SERVO = eINSTANCE.getServo_Servo();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.V_maxImpl <em>Vmax</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.V_maxImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getV_max()
     * @generated
     */
    EClass VMAX = eINSTANCE.getV_max();

    /**
     * The meta object literal for the '<em><b>Vmax</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VMAX__VMAX = eINSTANCE.getV_max_V_max();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.S_maxImpl <em>Smax</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.S_maxImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getS_max()
     * @generated
     */
    EClass SMAX = eINSTANCE.getS_max();

    /**
     * The meta object literal for the '<em><b>Smax</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMAX__SMAX = eINSTANCE.getS_max_S_max();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.H_maxImpl <em>Hmax</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.H_maxImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getH_max()
     * @generated
     */
    EClass HMAX = eINSTANCE.getH_max();

    /**
     * The meta object literal for the '<em><b>Hmax</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HMAX__HMAX = eINSTANCE.getH_max_H_max();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.V_minImpl <em>Vmin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.V_minImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getV_min()
     * @generated
     */
    EClass VMIN = eINSTANCE.getV_min();

    /**
     * The meta object literal for the '<em><b>Vmin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VMIN__VMIN = eINSTANCE.getV_min_V_min();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.S_minImpl <em>Smin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.S_minImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getS_min()
     * @generated
     */
    EClass SMIN = eINSTANCE.getS_min();

    /**
     * The meta object literal for the '<em><b>Smin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMIN__SMIN = eINSTANCE.getS_min_S_min();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.H_minImpl <em>Hmin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.H_minImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getH_min()
     * @generated
     */
    EClass HMIN = eINSTANCE.getH_min();

    /**
     * The meta object literal for the '<em><b>Hmin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HMIN__HMIN = eINSTANCE.getH_min_H_min();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.ColorImpl <em>Color</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.ColorImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getColor()
     * @generated
     */
    EClass COLOR = eINSTANCE.getColor();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR__COLOR = eINSTANCE.getColor_Color();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.BImpl <em>B</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.BImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getB()
     * @generated
     */
    EClass B = eINSTANCE.getB();

    /**
     * The meta object literal for the '<em><b>B</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute B__B = eINSTANCE.getB_B();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.GImpl <em>G</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.GImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getG()
     * @generated
     */
    EClass G = eINSTANCE.getG();

    /**
     * The meta object literal for the '<em><b>G</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute G__G = eINSTANCE.getG_G();

    /**
     * The meta object literal for the '{@link org.xtext.operations.impl.RImpl <em>R</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.operations.impl.RImpl
     * @see org.xtext.operations.impl.OperationsPackageImpl#getR()
     * @generated
     */
    EClass R = eINSTANCE.getR();

    /**
     * The meta object literal for the '<em><b>R</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute R__R = eINSTANCE.getR_R();

  }

} //OperationsPackage
