/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>R</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.operations.R#getR <em>R</em>}</li>
 * </ul>
 *
 * @see org.xtext.operations.OperationsPackage#getR()
 * @model
 * @generated
 */
public interface R extends EObject
{
  /**
   * Returns the value of the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' attribute.
   * @see #setR(int)
   * @see org.xtext.operations.OperationsPackage#getR_R()
   * @model
   * @generated
   */
  int getR();

  /**
   * Sets the value of the '{@link org.xtext.operations.R#getR <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' attribute.
   * @see #getR()
   * @generated
   */
  void setR(int value);

} // R
