/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Smax</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.operations.S_max#getS_max <em>Smax</em>}</li>
 * </ul>
 *
 * @see org.xtext.operations.OperationsPackage#getS_max()
 * @model
 * @generated
 */
public interface S_max extends EObject
{
  /**
   * Returns the value of the '<em><b>Smax</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smax</em>' attribute.
   * @see #setS_max(int)
   * @see org.xtext.operations.OperationsPackage#getS_max_S_max()
   * @model
   * @generated
   */
  int getS_max();

  /**
   * Sets the value of the '{@link org.xtext.operations.S_max#getS_max <em>Smax</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Smax</em>' attribute.
   * @see #getS_max()
   * @generated
   */
  void setS_max(int value);

} // S_max
