/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Solution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.operations.Solution#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.operations.Solution#getAngle_res <em>Angle res</em>}</li>
 * </ul>
 *
 * @see org.xtext.operations.OperationsPackage#getSolution()
 * @model
 * @generated
 */
public interface Solution extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.operations.OperationsPackage#getSolution_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.operations.Solution#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Angle res</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.Angle_res}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle res</em>' containment reference list.
   * @see org.xtext.operations.OperationsPackage#getSolution_Angle_res()
   * @model containment="true"
   * @generated
   */
  EList<Angle_res> getAngle_res();

} // Solution
