/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vmax</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.operations.V_max#getV_max <em>Vmax</em>}</li>
 * </ul>
 *
 * @see org.xtext.operations.OperationsPackage#getV_max()
 * @model
 * @generated
 */
public interface V_max extends EObject
{
  /**
   * Returns the value of the '<em><b>Vmax</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vmax</em>' attribute.
   * @see #setV_max(int)
   * @see org.xtext.operations.OperationsPackage#getV_max_V_max()
   * @model
   * @generated
   */
  int getV_max();

  /**
   * Sets the value of the '{@link org.xtext.operations.V_max#getV_max <em>Vmax</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vmax</em>' attribute.
   * @see #getV_max()
   * @generated
   */
  void setV_max(int value);

} // V_max
