/**
 * generated by Xtext 2.26.0
 */
package org.xtext.cPtester;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.xtext.operations.Initial;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Given</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.cPtester.Given#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.cPtester.Given#getInitial <em>Initial</em>}</li>
 * </ul>
 *
 * @see org.xtext.cPtester.CPtesterPackage#getGiven()
 * @model
 * @generated
 */
public interface Given extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.cPtester.CPtesterPackage#getGiven_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.cPtester.Given#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Initial</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.operations.Initial}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial</em>' containment reference list.
   * @see org.xtext.cPtester.CPtesterPackage#getGiven_Initial()
   * @model containment="true"
   * @generated
   */
  EList<Initial> getInitial();

} // Given
