/*
 * generated by Xtext 2.26.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OperationsUiModule extends AbstractOperationsUiModule {

	public OperationsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
