/*
 * generated by Xtext 2.26.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.operations.ui.internal.OperationsActivator;

public class OperationsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return OperationsActivator.getInstance().getInjector("org.xtext.Operations");
	}

}
